// IMPORTANT FOR INTERVIEW AND OA
// WHY WE USE DISJOINT SET:
// TO FIND TWO OR MORE NODES ARE OF SAME COMPONENT OF GRAPH OR NOT AT CONSTANT TIME?
// USED IN DYNAMIC GRAPHS AS WELL --> GRAPHS WHICH CHANGE THEIR CONFIGURATIONS AT EVERY MOMENT
// USED TO FIND PARENT
// USED TO FIND UNION (RANK,PARENT)

// PSEUDOCODE OF UNION (U,V)
// 1. FIND ULTIMATE PARENT OF U & V , PU(ULITMATE PARENT OF U) , PV(ULTIMATE PARENT OF V)
// 2. FIND RANK OF PU,PV
// 3. CONNECT SMALLER RANK TO THE LARGER RANK ALWAYS
// TC OF UNION OPERATION: O(4 * ALPHA)
// TC OF FIND PARENT OPERATION : O(4 * ALPHA) 