// QUES 12 : IMPORTANT
// QUES 15 : MAP IMPORTANT CONCEPT
// QUES 16 : SAME TO QUES 15
// QUES 17 : DUTCH NATIONAL FLAG ALGO
// QUES 18 : MOORE'S VOTING ALGO
// QUES 19 : KADANES'S ALGORITHM
// QUES 23 : IMP
// QUES 29 : IMP MAP CONCEPT
// QUES 32 , 33 , 34 : IMPORTANT
// QUES 40  FEW CONCEPT LEFT TO LEARN
// QUES 41 AND 41 --> MERGE SORT BASED 