// DIJKSTRA IS FAIL FOR NEGATIVE WEIGHTED GRAPHS
// BELLMAN FORD WORKS FOR NEGATIVE WEIGHTED GRAPHS TO REACH ALL NODES FROM SRC NODE
// BELLMAN IS USED ONLY FOR DIRECTED GRAPHS

//ALGO
// 1 RELAX ALL THE EDGES N-1 TIMES SEQUENTIALLY
// 2 IF(DIST[U]+WT < DIST[V]){
//      DIST[V]=DIST[U]+WT
//   }

//HOW WE DETECT CYCLE -->
// ON Nth ITERATION, THE RELAXATION WILL BE DONE AND IF
// THE DIST[] ARRAY GETS REDUCED THEN CYCLE EXIST. 