// TREE IS A HEIRARCHICAL DATA STRUCTURE

// TYPES OF BINARY TREES 
// 1 FULL BT  
// 2 COMPLETE BT
// 3 PERFECT BT
// 4 BALANCED BT
// 5 DEGENERATE TREE

// FULL BT 
// EITHER HAS 0 OR 2 CHILDREN

// COMPLETE BT
// ALL LEVELS ARE COMPLETELY FILLED EXCEPT LAST LEVEL
// LAST LEVEL HAS ALL NODES AS LEFT AS POSSIBLE

// PERFECT BT
// ALL LEAF NODES ARE AT SAME LEVEL

// BALANCED BT
// HEIGHT OF BT AT MAX OF LOG(NO. OF NODES)

// DEGENERATE TREES
// EVERY NODE HAS A SINGLE CHILD 
// IT SHOULD BE STRAIGHT

// TYPES OF TRAVERSAL TECHNIQUE
// 1 DFS
// 2 BFS  (LEVEL WISE TRAVERSAL)

// DFS TECHNIQUES INCLUDE :
// 1 INORDER TRAVERSAL (LEFT , ROOT, RIGHT)
// 2 PRE ORDER TRAVERSAL (ROOT, LEFT, RIGHT)
// 3 POST ORDER TRAVERSAL (LEFT, RIGHT, ROOT)