// THIS ALGO IS USED TO FIND SHORTEST DISTANCE TO ALL NODES FROM MULTIPLE SOURCES
// MULTIPLE SOURCE SHORTEST PATH ALGO
// ALSO USED TO DETECT NEGATIVE CYCLE IN DAG OR DG OR UDG

//HOW TO DETECT NEGATIVE CYCLE
// IF(COST[I][I]<0){
//      NEGATIVE CYCLE EXIST 
//  }